name: build
on: push

jobs:
  publish:
    name: Publish pdf
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.0.4]
    container:
      image: amutake/satysfi:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install saxon
        run: apt install libsaxon-java -y
      - name: Build with SATySFi
        run: |
          export HOME=/root
          eval $(opam env)
          make
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: cv
          path: cv_2020_Spring.pdf
